### ISSUE TITLE
Making a get route more effecient... maybe?

### ISSUE THREAD

**Issue by danielmrichter** [PrimeAcademy/pinnacles-syllabus#13]
## Describe the Issue!

**What do you want to happen?**
Well, what is happening. I ask for data, I get data.

The question is more, is this going to cause problems in the future, since I'm making a ton sql queries to get the data. I want to figure out if there's a way to be more efficient, or if I'm going to create a problem when working with really large data sets.

It is in the beetData.router.js. it is the GET /api/beet_data/:siteid. https://github.com/pinnaclescultivate/cultivate-dashboard
**What is actually happening?**

## What have you tried? Who have you asked?

Research. Bit above my pay grade, though.

## What branch is your code on? Did you git push?

Main. https://github.com/pinnaclescultivate/cultivate-dashboard

**Comment by matthew-black** [comment]
We talked through the idea of subqueries, and here's what we were playing with:

```sql
SELECT "sites"."site" AS "site_name", 
JSONB_AGG(JSONB_BUILD_OBJECT(
  'temperature', "beet_data"."temperature",
  'beet_data_id', "beet_data"."id",
  'time', "beet_data"."temperature_time")) AS "dayActuals",
"pilers"."id" AS "piler_id", 
"pilers"."name" AS "piler_name",
"blah"."avgTempOfEachDay"
FROM "pilers"
	JOIN
	(
	  SELECT 
    AVG("beet_data"."temperature") AS "avgTempOfEachDay",
    DATE_TRUNC('day', "beet_data"."temperature_time") AS "day",
    "pilers"."id"
--    "pilers"."id" as "pilerId"
	      FROM "pilers"
        JOIN "beet_data" ON "pilers"."id" = "beet_data"."piler_id"
    	JOIN "sites" ON "pilers"."site_id" = "sites"."id"
        WHERE "sites"."id" = 1
        AND "beet_data"."temperature_time" >= NOW() - INTERVAL '1 month'
        GROUP BY "pilers"."id", "day"
        ORDER BY "day"
	) AS "blah" ON "pilers"."id" = "blah"."pilerId"
    JOIN "sites" ON "pilers"."site_id" = "sites"."id"
    JOIN "beet_data" ON "pilers"."id" = "beet_data"."piler_id"
    WHERE "sites"."id" = 1
    AND "beet_data"."temperature_time" >= CURRENT_DATE
	  AND "beet_data"."temperature_time" < CURRENT_DATE + INTERVAL '1 day'
    GROUP BY "sites"."site", "pilers"."id", "pilers"."name", "blah";
```

The subquery's output currently is shaped like this:

![Screenshot 2024-10-02 at 10 27 03 AM](https://github.com/user-attachments/assets/e8075240-3356-4c51-9d09-c4a0ce1c6d5d)


If we want to be able to JOIN into the subquery's output, we'll need to ensure the rows returned by the subquery are **one row per each piler id**. So, you'll need to think through how the subquery output could be transformed to this:
```
[
  { piler_id: 1, month_data: [{...},{...}] },
  { piler_id: 2, month_data: [{...},{...}] }
  { piler_id: 3, month_data: [{...},{...}] },
]

```
