### ISSUE TITLE
GooglePlacesAutoComplete

### ISSUE THREAD

**Issue by emolden** [PrimeAcademy/pinnacles-syllabus#14]
## Describe the Issue!

**What do you want to happen?**
I would like to be able to have the page render without an error, input an address and as I type the suggested addresses appear, and when I hit "Submit" the address I typed in/selected is console logged.

**What is actually happening?**

The page isn't loading because I have errors. I think I downloaded too many versions of things but I can't figure out how to backtrack. 
![image](https://github.com/user-attachments/assets/72c8b26e-eb69-4b95-b353-f0c84021ff8f)
![image](https://github.com/user-attachments/assets/13189da1-5b99-43c4-b29b-a7336b0bb2df)

## What have you tried? Who have you asked?
I have gone over everything with Brii and Jen. I have also tried putting my code into chatgpt with the error messages.
![image](https://github.com/user-attachments/assets/9aefc312-2eb8-4147-a963-068a8546ca67)

I have tried commenting out as much of the code as I can to issolate the issue. I have my code down to the bare bones. Since I think it's a problem with my dependencies, this debugging strategy doesn't seem to be helping. 

## What branch is your code on? Did you git push?
Yes, googlePlacesAutoComplete

**Comment by matthew-black** [comment]
The `@emotion/react` thing is just a warning, so not likely breaking stuff. That said, I found someone with a [similar issue](https://github.com/emotion-js/emotion/discussions/2795). In that thread, it's recommended to run this terminal command, which should help you diagnose which libraries are relying on conflicting versions of `@emotion/react`:

* `npm ls @emotion/react`

---

We'll have to dig into the Google thing so I can get my eyes on it.
