### ISSUE TITLE
How to have an input value effect another input value

### ISSUE THREAD

**Issue by Jenniphoher** [PrimeAcademy/pinnacles-syllabus#16]
## Describe the Issue!

**What do you want to happen?**

HI! For our mortgage calculator, I wanted the down payment in dollar amount to populate in it's input if the user puts in a percentage. And vice versa!

**What is actually happening?**

![Screenshot 2024-10-09 at 9 00 49 PM](https://github.com/user-attachments/assets/11072658-8e14-4b24-ad62-37c9248a1e57)
![Screenshot 2024-10-09 at 9 01 04 PM](https://github.com/user-attachments/assets/6404b247-17d3-487c-91b1-2792588e4021)
<img width="317" alt="Screenshot 2024-10-09 at 9 05 45 PM" src="https://github.com/user-attachments/assets/9221b6ae-a2a6-48ab-a29d-0707a0bf970c">

## What have you tried? Who have you asked?

If you look at the screenshots, I've tried having the desired values change onChange. I'm not sure if that's right or not or if I was on the right track. It did stop me from putting in any value in its input if I had the e.target.querySelector in the onChange though. I also tried messing with value={downPayment}, it didn't seem to work either.

## What branch is your code on? Did you git push?
OH, okay! I'll push it now! My branch is feature-calculator.

**Comment by matthew-black** [comment]
@Jenniphoher I think you just need to update the value of the other input's state. Like:
<img width="1156" alt="Screenshot 2024-10-09 at 11 29 55 PM" src="https://github.com/user-attachments/assets/e6d8d53f-77c6-4bcd-822e-f5a96211172a">

That said, I'd create a function above all the JSX, then just use that in the `onChange`. Like:

```js
// Example of what I'm thinking:
const handleDownPaymentChange = (e) => {
  const newPercentage = (e.target.value / purchasePrice) * 100;
  setDownPaymentPercentage(newPercentage);
  setDownPayment(e.target.value);
}

// Then, down in the JSX on the input's onChange:
  onChange={handleDownPaymentChange}
```

Typically, you don't want to do more than *one straightforward line of code* inside an `onChange`. (Things start to look real messy real fast.)

Let me know if this helps, or if you have follow-up questions!

P.S. I'm not sure why I'm awake right now, but I saw this and figured I'd give you a quick explanation in hopes that you'll get some *really good sleep* tonight. 🙂

**Comment by Jenniphoher** [comment]
Thanks, Matt!!! I'll give it a try! I thought setWhatever() ended a function like a return, so I didn't think to use it twice! I hope you got really good sleep too!!

**Comment by Jenniphoher** [comment]
It works, Matt! Such a simple issue... definitely not a worthy issue to ticket! 😭
