### ISSUE TITLE
Issue with Routes adding on to the route address

### ISSUE THREAD

**Issue by bpol87** [PrimeAcademy/pinnacles-syllabus#2]
## Describe the Issue!

**What do you want to happen?**
I would like to operate between pages seamlessly without the routes adding extra #/[route-name] to the url.

**What is actually happening?**
I am seeing extra routes added to the url and it is causing a 404 Error break.

![Screenshot 2024-09-03 at 4 42 47 PM](https://github.com/user-attachments/assets/a82f6c36-1e76-417d-95a2-ccad87f67808)

## What have you tried? Who have you asked?
I have tried playing with the routes in the App.jsx file but I can't track how the app is adding the routes.
I also have tried googling the answer but it seems the specific problem I have with the checklist is not a common enough issue.

I know it has to do with the history.push but I dont think i understand fully what is happening

## What branch is your code on? Did you git push?

https://github.com/bpol87/choralsync/tree/checklist-error

**Comment by danielmrichter** [comment]
I know I'm not Matt, but I wouldn't be surprised if it had to do with the form's default behavior of refreshing the page. Try catching the event in the arguments and adding in a event.preventDefault().
