### ISSUE TITLE
Warning error in my client side Console saying that <p> is nested as a descendant of another <p>

### ISSUE THREAD

**Issue by bpol87** [PrimeAcademy/pinnacles-syllabus#4]
## Describe the Issue!

**What do you want to happen?**
no warning

**What is actually happening?**
Seeing a warning saying that a <p> is nested inside of another <p> but when i went through the file I checked each <p> and don't see one that is nested inside another.

![Screenshot 2024-09-05 at 11 28 36 AM](https://github.com/user-attachments/assets/1f086b76-a61b-4886-a08e-9c73938a8c63)

## What have you tried? Who have you asked?
I have tried going through the error code and also my own file code and I don't see the error.

I know what page it is that is causing the issue but again i can't find where the issue is originating from.

## What branch is your code on? Did you git push?
https://github.com/bpol87/choralsync/tree/review-error

**Comment by DoctorHowser** [comment]
found the nested p tag!
