### ISSUE TITLE
Vite and Outlet

### ISSUE THREAD

**Issue by mntokijabe** [PrimeAcademy/pinnacles-syllabus#5]
## Describe the Issue!

I'm trying to use Outlet from react-router-dom so I can have my layout show the header and sidebar on each page with the content in the content area as a child of the outlet

**What is actually happening?**
It worked for a little bit as I clicked on some nav buttons... but then I refreshed and all went blank with this error coming up:
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-router-dom.js?v=b538c4ca' does not provide an export named 'Outlet'

## What have you tried? Who have you asked?
-I've taken Outlet out of the import list and the error shows up as soon as I type Outlet back into the import set
- installed react-router-dom@6.26.1  (latest version)
-I've googled "does vite conflict with Outlet" and found a few threads that say there is a conflict when in build production. I've followed a couple of those suggestions including updating rollup

I haven't asked anyone in my pod as it's lunchtime. Also, I'm assuming no one else may even be aware of Outlet as I just found it this morning.

## What branch is your code on? Did you git push?
https://github.com/mntokijabe/music-notes/tree/routes-with-outlet-issue

**Comment by DoctorHowser** [comment]
Outlet is v6, meant for subroutes. We rolled back to v4/5 and used {children} instead
