### ISSUE TITLE
Modalsss

### ISSUE THREAD

**Issue by SwordLegz** [PrimeAcademy/pinnacles-syllabus#7]
## Describe the Issue!
I've been having a difficult time figuring out how to properly implement modals into my code.
There've been sooo many tutorials and articles I've gone through, and they all seem so different from each other.
I've tried a number of ways to get this to work but I think I'm getting confused on where in my code it should be going.

**What do you want to happen?**
I want to have each CakeBiteItem in ShopCakeBites to pop up as a modal when clicked with further details about that specific flavor.

**What is actually happening?**

Nothing yet. Each time I enter in code, either nothing happens (not even errors in the console) or it breaks the whole page/code.

## What have you tried? Who have you asked?
I've asked roomie Chris a bit, I looked over some of his code from when he's done modals; as well as lots of googling and Youtubing.

I believe it's just the modal coding itself. I might just be putting it in the wrong place...

## What branch is your code on? Did you git push?
Main.

Commited & Pushed.

**Comment by matthew-black** [comment]
Gonna just implement the feature without modals for now. Onward!
